config/routes.rb
Rails.application.routes.draw do

   get 'users/:id/moon', to: 'users#moon', as: 'moon'

  resources :users do
    resources :sessions
  end

  resources :welcomes

  root 'welcomes#index'

end

app/models/fact.rb
class Fact < ActiveRecord::Base
  has_many :sessions
  has_many :users, through: :sessions

end

app/models/session.rb
class Session < ActiveRecord::Base

  belongs_to :user
  belongs_to :fact
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :sessions
  has_many :facts, through: :sessions

  # def self.search(search)
  #   where("name LIKE ?", "%#{search}%") 
  #   where("location LIKE ?", "%#{search}%")

  # end

  def self.search(search)
      where('name LIKE ?', "%#{search}%")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
    @sessions = Session.all
    @user= User.all
  
  end

  def new
    user = User.find(params[:user_id])
    @session = user.sessions.build
  end

  def create
    user = User.find(params[:user_id])
    @session = user.sessions.new(session_params)
    @user = User.find(params[:user_id])

    if @session.save
      flash[:notice] = 'You added a new session'
      redirect_to @user
    else
      flash.now[:error] = "Error: #{session.errors.full_messages}"
      render :new
    end
  end

  def show
    user = User.find(params[:post_id])
    @session = user.sessions.find(params[:id])
  end

  def edit
    user = User.find(params[:user_id])
    @session = user.sessions.find(params[:id])
  end

  def update
    user = User.find(params[:user_id])
    @session = user.sessions.find(params[:id])

     if @session.update_attributes(session_params)
      redirect_to user
    else
      render :edit
    end
  end

  def destroy
    user = User.find(params[:user_id])
    @session = user.sessions.find(params[:id])
    @session.destroy
    redirect_to user
  end

  private

  def session_params
    params.require(:session).permit(:activity, :location, :distance)
  end

 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    # @users = User.all.order('created_at DESC')
     @users = User.all
    if params[:search]
      @users = User.search(params[:search]).order("created_at DESC")
    else
      @users = User.all.order('created_at DESC')
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:notice] = 'user created successfully!'
      redirect_to @user
    else
      flash.now[:error] = "Error: #{user.errors.full_messages}"
      render :new
    end
  end

  def show
    @user = User.find(params[:id])

  end

  def edit
    @user = User.find(params[:id])

  end

  def update
    user = User.find(params[:id])

    if user.update_attributes(user_params)
      redirect_to user
    else
      render :edit
    end
  end

  def destroy
    user = User.find(params[:id]).destroy

    redirect_to root_path
  end

  def moon
    @user = User.find(params[:id])

    @sum = 0
    @user.sessions.each do |session|
    @sum = @sum + session.distance.to_i
    end 
    gon.sum = @sum
    
  end 

  private
  def user_params
    params.require(:user).permit(:name, :age, :location)
  end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  def index
    @users = User.all
    end
 end    

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_controller_helper.rb
module UsersControllerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spacewalk</title>
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.3/normalize.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_user.html.erb
<% @users.each do |user| %>
  <div>
    <h1><%= link_to user.name, user %></h1>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1> <%=link_to 'moonwalk', welcomes_path, class: "little_welcomer" %> </h1>

<h1 class = "page_title"> Edit <%=@user.name%> </h1>

<div class = "form_container">
<%= form_for @user do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :age %>
    <%= form.text_field :age %>
  </div>
  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>
  <div class="action">
    <%= form.submit 'Update' %>
  </div>
</div>
<% end %>

app/views/users/index.html.erb
<h1> <%=link_to 'moonwalk', welcomes_path, class: "little_welcomer" %> </h1>

<h1 class = "page_title"> Existing user </h1>

<div class = "search_users">
<%= form_tag(users_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search users" %>
  <%= submit_tag "Search" %>

<% end %>

</div>

<h2 class="profile_select">Select your profile from below.</h2> <h2 class = "not_here"> <%=link_to "Not here?", new_user_path %></h2>

<div class = "users_select">
<% if @users.present? %>
  <%= render "user" %>
  <% else %>
  <p>There are no users containing the term(s) <%= params[:search] %>.</p>
<% end %>
<div>

app/views/users/moon.html.erb
 <%= Gon::Base.render_data %>


<div id= "info_container">
  <h1> <%=link_to 'moonwalk', welcomes_path, class: "little_welcomer" %> </h1>
  <h1 class= "moon_page_title"> <%= @user.name%> </h1>
  <button id ="calculate_moon"> >Calculate progress</button>
</div>

<div id = "planet_container">

    <div id = "redline">
    <hr id="thelineitself">
    </div>

    <h2 id="how_far"><%= @sum %> / 384,400 km (<%= ((@sum/384400.0)*100).round(2)%>%)</h2>
    <h1 id="to_go"> Only <%= 384400 - @sum%>km to go! </h1>
    <h2 id="back_to_user"><%= link_to '>Back to your profile', user_path(@user) %></h2>

    <img id = "earthpic" src="http://orig10.deviantart.net/ae54/f/2010/326/5/1/51fe8413c296378bbc0563daf917459b-d33emut.png">

    <img id = "moonpic" src="http://images.clipartpanda.com/moon-clip-art-119498436179961113moon_charles_mccolm_01.svg.med.png">

</div>

app/views/users/new.html.erb
<h1> <%=link_to 'moonwalk', welcomes_path, class: "little_welcomer" %> </h1>

<h1 class= "page_title">New user</h1>

<div class = "form_container">
  <%= form_for @user do |form| %>
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
    <div class="field">
      <%= form.label :age %>
      <%= form.text_field :age %>
    </div>
    <div class="field">
      <%= form.label :location %>
      <%= form.text_field :location %>
    </div>
    <div class="action">
      <%= form.submit 'Create User' %>
    </div>

  <% end %>
</div>

app/views/users/show.html.erb
<h1> <%=link_to 'moonwalk', welcomes_path, class: "little_welcomer" %> </h1>


<br>
<div id="user_header">
    <h1 id = "usernameshow"><%= @user.name %></h1>


    <%= link_to 'Edit | ', edit_user_path(@user) %>
    <%= link_to 'Delete | ', @user, method: :delete, data: { confirm: "Are you sure?" } %>
    <%= link_to 'New session | ', new_user_session_path(@user) %>
    <%= link_to 'Moon progress ', moon_path(@user) %>

</div>

<div id= "glance_container">
  <h2 id="glance_title" href:"#"> At a glance </h2><div class="arrow-down"></div>

  <div id= "glance_info">
    Joined: <%= time_ago_in_words(@user.created_at) %> ago
    <p><font-color = "white">Age:</font> <%= @user.age %></p>
    <p>Location: <%= @user.location %></p>

    <!-- Total distance -->
      <% sum = 0 %>
      <% @user.sessions.each do |session| %>
      <%  sum = sum + session.distance.to_i %>
      <% end %>
    <p> Total distance: <%= sum %>km</p>

    <!-- Average distance -->
    <% all_distance = @user.sessions.pluck(:distance) %>
    <% all_distance.map! { |s| s.to_i} %>
    <% all_distance %>


    <p> Average distance per session: <%= all_distance.inject{ |sum, el| sum + el }.to_f / all_distance.size %>km  </p>

    <!-- 
    Favourite place distance -->
      
    <% arr = @user.sessions.pluck(:location) %>
    <% freq = arr.inject(Hash.new(0)) { |h,v| h[v] += 1; h } %>
    <p> Favourite place to exercise: <%= arr.max_by { |v| freq[v] } %> </p>

    <p> Total sessions logged: <%=@user.sessions.count%> <p>

  </div>
</div>

<div id= "session_container">

    <h2 id="session_title" href:"#"> Session history </h2><div class="arrow-down"></div>

    <div id= "session_info">
      <% @user.sessions.each do |session|%>
        <p>Activity: <%= session.activity %></p>
        <p>Distance: <%= session.distance %></p>
        <p>Location: <%= session.location %></p>
        <p>Date: 31/05/1987</p>
        <%= link_to 'Edit | ', edit_user_session_path(session.user, session)%>
        <%= link_to 'Delete', [session.user, session], method: :delete, data: { confirm: "Are you sure?" } %>
        <br>
      <% end %>
    </div>

</div>

app/views/welcomes/index.html.erb
<div id="welcome-index">
  <h1> <%=link_to 'moonwalk', welcomes_path, class: "welcomer" %> </h1>
  <button type="button"class="existing-button"> <%= link_to 'Existing user', users_path %></button>
  <button type="button"class="new-button"><%= link_to 'New user', new_user_path %></button>

</div>